# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnAceptar = QtWidgets.QPushButton(self.centralwidget)
        self.btnAceptar.setGeometry(QtCore.QRect(160, 390, 75, 23))
        self.btnAceptar.setObjectName("btnAceptar")
        self.btnSalir = QtWidgets.QPushButton(self.centralwidget)
        self.btnSalir.setGeometry(QtCore.QRect(350, 390, 75, 23))
        self.btnSalir.setObjectName("btnSalir")
        self.editApel = QtWidgets.QLineEdit(self.centralwidget)
        self.editApel.setGeometry(QtCore.QRect(100, 140, 221, 21))
        self.editApel.setObjectName("editApel")
        self.editDni = QtWidgets.QLineEdit(self.centralwidget)
        self.editDni.setGeometry(QtCore.QRect(100, 90, 113, 20))
        self.editDni.setObjectName("editDni")
        self.editNome = QtWidgets.QLineEdit(self.centralwidget)
        self.editNome.setGeometry(QtCore.QRect(420, 140, 141, 20))
        self.editNome.setObjectName("editNome")
        self.lblApel = QtWidgets.QLabel(self.centralwidget)
        self.lblApel.setGeometry(QtCore.QRect(30, 140, 47, 21))
        self.lblApel.setObjectName("lblApel")
        self.lblDni = QtWidgets.QLabel(self.centralwidget)
        self.lblDni.setGeometry(QtCore.QRect(30, 90, 47, 13))
        self.lblDni.setObjectName("lblDni")
        self.lblNome = QtWidgets.QLabel(self.centralwidget)
        self.lblNome.setGeometry(QtCore.QRect(360, 140, 47, 16))
        self.lblNome.setObjectName("lblNome")
        self.lineInf = QtWidgets.QFrame(self.centralwidget)
        self.lineInf.setGeometry(QtCore.QRect(17, 330, 581, 31))
        self.lineInf.setFrameShape(QtWidgets.QFrame.HLine)
        self.lineInf.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineInf.setObjectName("lineInf")
        self.lineSup = QtWidgets.QFrame(self.centralwidget)
        self.lineSup.setGeometry(QtCore.QRect(17, 50, 581, 20))
        self.lineSup.setFrameShape(QtWidgets.QFrame.HLine)
        self.lineSup.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineSup.setObjectName("lineSup")
        self.lblTitle = QtWidgets.QLabel(self.centralwidget)
        self.lblTitle.setGeometry(QtCore.QRect(250, 20, 121, 20))
        self.lblTitle.setObjectName("lblTitle")
        self.lblValido = QtWidgets.QLabel(self.centralwidget)
        self.lblValido.setGeometry(QtCore.QRect(230, 90, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Forte")
        font.setPointSize(14)
        self.lblValido.setFont(font)
        self.lblValido.setText("")
        self.lblValido.setObjectName("lblValido")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSalir = QtWidgets.QAction(MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.menuArchivo.addAction(self.actionSalir)
        self.menubar.addAction(self.menuArchivo.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnAceptar.setText(_translate("MainWindow", "Aceptar"))
        self.btnSalir.setText(_translate("MainWindow", "Salir"))
        self.lblApel.setText(_translate("MainWindow", "Apellidos"))
        self.lblDni.setText(_translate("MainWindow", "DNI"))
        self.lblNome.setText(_translate("MainWindow", "Nombre"))
        self.lblTitle.setText(_translate("MainWindow", "    GESTION CLIENTES"))
        self.menuArchivo.setTitle(_translate("MainWindow", "Archivo"))
        self.actionSalir.setText(_translate("MainWindow", "Salir"))
        self.actionSalir.setShortcut(_translate("MainWindow", "Ctrl+S"))
